from django.urls import path
from .views.public import ana_sayfa, duyurular_sayfasi, kayit_ol, giris_yap, cikis_yap, fikstur_sayfasi
from .views.user import profil, basketbol_takim_yonetimi, futbol_takim_yonetimi
from .views.admin import (
    admin_dashboard, admin_basketbol_listesi, admin_futbol_listesi,
    admin_basketbol_detay, admin_futbol_detay, admin_basketbol_sil, admin_futbol_sil,
    admin_duyurular, admin_duyuru_duzenle, admin_duyuru_sil, admin_duyuru_toggle,
    admin_kullanicilar, admin_export_basketbol, admin_export_futbol,
    admin_export_tum, admin_export_kullanicilar, excel_indir_basketbol, excel_indir_futbol,
    ozel_yonetim_paneli, admin_site_ayarlari, admin_fikstur, admin_eslesme_olustur,
    admin_turnuva_ekle, admin_turnuva_sil, admin_mac_duzenle, admin_mac_sil
)

urlpatterns = [
    path('', ana_sayfa, name='ana_sayfa'),
    path('duyurular/', duyurular_sayfasi, name='duyurular'),
    path('kayit/', kayit_ol, name='kayit_ol'),
    path('giris/', giris_yap, name='giris_yap'),
    path('cikis/', cikis_yap, name='cikis_yap'),
    path('profil/', profil, name='profil'),
    path('basketbol-yonetim/', basketbol_takim_yonetimi, name='basketbol_yonetim'),
    path('futbol-yonetim/', futbol_takim_yonetimi, name='futbol_yonetim'),
    path('fikstur/', fikstur_sayfasi, name='fikstur'),
    path('yonetim/', admin_dashboard, name='admin_dashboard'),
    path('yonetim/basketbol/', admin_basketbol_listesi, name='admin_basketbol_listesi'),
    path('yonetim/basketbol/<int:pk>/', admin_basketbol_detay, name='admin_basketbol_detay'),
    path('yonetim/basketbol/<int:pk>/sil/', admin_basketbol_sil, name='admin_basketbol_sil'),
    path('yonetim/futbol/', admin_futbol_listesi, name='admin_futbol_listesi'),
    path('yonetim/futbol/<int:pk>/', admin_futbol_detay, name='admin_futbol_detay'),
    path('yonetim/futbol/<int:pk>/sil/', admin_futbol_sil, name='admin_futbol_sil'),
    path('yonetim/duyurular/', admin_duyurular, name='admin_duyurular'),
    path('yonetim/duyurular/<int:pk>/duzenle/', admin_duyuru_duzenle, name='admin_duyuru_duzenle'),
    path('yonetim/duyurular/<int:pk>/sil/', admin_duyuru_sil, name='admin_duyuru_sil'),
    path('yonetim/duyurular/<int:pk>/toggle/', admin_duyuru_toggle, name='admin_duyuru_toggle'),
    path('yonetim/kullanicilar/', admin_kullanicilar, name='admin_kullanicilar'),
    path('yonetim/excel-basketbol/', admin_export_basketbol, name='admin_export_basketbol'),
    path('yonetim/excel-futbol/', admin_export_futbol, name='admin_export_futbol'),
    path('yonetim/excel-tum/', admin_export_tum, name='admin_export_tum'),
    path('yonetim/excel-kullanicilar/', admin_export_kullanicilar, name='admin_export_kullanicilar'),
    path('yonetim/eski/', ozel_yonetim_paneli, name='ozel_yonetim'),
    path('yonetim/excel-basketbol/eski/', excel_indir_basketbol, name='excel_indir_basketbol'),
    path('yonetim/excel-futbol/eski/', excel_indir_futbol, name='excel_indir_futbol'),
    path('yonetim/ayarlar/', admin_site_ayarlari, name='admin_site_ayarlari'),
    path('yonetim/fikstur/', admin_fikstur, name='admin_fikstur'),
    path('yonetim/fikstur/eslesme-olustur/', admin_eslesme_olustur, name='admin_eslesme_olustur'),
    path('yonetim/turnuva/ekle/', admin_turnuva_ekle, name='admin_turnuva_ekle'),
    path('yonetim/turnuva/<int:pk>/sil/', admin_turnuva_sil, name='admin_turnuva_sil'),
    path('yonetim/mac/<int:pk>/duzenle/', admin_mac_duzenle, name='admin_mac_duzenle'),
    path('yonetim/mac/<int:pk>/sil/', admin_mac_sil, name='admin_mac_sil'),
]
