# Generated by Django 5.2.15 on 2026-06-28 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('icerik', models.TextField(verbose_name='Duyuru İçeriği')),
                ('yayinlanma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Yayında mı?')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-yayinlanma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='BasketbolTakimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim_adi', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('telefon', models.CharField(max_length=15, verbose_name='İletişim Telefonu')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kaptan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basketbol_takimi', to=settings.AUTH_USER_MODEL, verbose_name='Takım Kaptanı')),
            ],
            options={
                'verbose_name': 'Basketbol Takımı',
                'verbose_name_plural': 'Basketbol Takımları',
            },
        ),
        migrations.CreateModel(
            name='BasketbolOyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyuncular', to='turnuva.basketboltakimi')),
            ],
            options={
                'verbose_name': 'Basketbol Oyuncusu',
                'verbose_name_plural': 'Basketbol Oyuncuları',
            },
        ),
        migrations.CreateModel(
            name='FutbolTakimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim_adi', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('telefon', models.CharField(max_length=15, verbose_name='İletişim Telefonu')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kaptan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='futbol_takimi', to=settings.AUTH_USER_MODEL, verbose_name='Takım Kaptanı')),
            ],
            options={
                'verbose_name': 'Futbol Takımı',
                'verbose_name_plural': 'Futbol Takımları',
            },
        ),
        migrations.CreateModel(
            name='FutbolOyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('takim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oyuncular', to='turnuva.futboltakimi')),
            ],
            options={
                'verbose_name': 'Futbol Oyuncusu',
                'verbose_name_plural': 'Futbol Oyuncuları',
            },
        ),
    ]
