# Generated by Django 5.2.15 on 2026-06-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnuva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketboloyuncu',
            name='tc_no',
            field=models.CharField(max_length=255, verbose_name='TC Kimlik No'),
        ),
        migrations.AlterField(
            model_name='futboloyuncu',
            name='tc_no',
            field=models.CharField(max_length=255, verbose_name='TC Kimlik No'),
        ),
    ]
