# Generated by Django 5.2.15 on 2026-06-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnuva', '0002_alter_basketboloyuncu_tc_no_alter_futboloyuncu_tc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvkk_text', models.TextField(verbose_name='KVKK Onay Metni')),
                ('kayit_bitis_tarihi', models.DateTimeField(verbose_name='Kayıt Bitiş Tarihi/Saati')),
                ('whatsapp_api_token', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp API Token')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp Phone Number ID')),
                ('whatsapp_recipient_number', models.CharField(blank=True, max_length=20, verbose_name='Bildirim Gönderilecek Numara')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Turnuva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Turnuva Adı')),
                ('brans', models.CharField(choices=[('basketbol', 'Basketbol'), ('futbol', 'Futbol')], max_length=20, verbose_name='Branş')),
                ('durum', models.CharField(choices=[('kayit_acik', 'Kayıt Açık'), ('eslesme_yapildi', 'Eşleşme Yapıldı'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı')], default='kayit_acik', max_length=20, verbose_name='Durum')),
                ('kayit_bitis_tarihi', models.DateTimeField(verbose_name='Kayıt Bitiş Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Turnuva',
                'verbose_name_plural': 'Turnuvalar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SayfaGoruntuleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_yolu', models.CharField(choices=[('ana_sayfa', 'Ana Sayfa'), ('kayit', 'Kayıt Sayfası'), ('giris', 'Giriş Sayfası'), ('profil', 'Profil Sayfası'), ('fikstur', 'Fikstür Sayfası'), ('duyurular', 'Duyurular Sayfası'), ('basketbol_yonetim', 'Basketbol Takım Yönetimi'), ('futbol_yonetim', 'Futbol Takım Yönetimi'), ('admin_dashboard', 'Admin Dashboard')], max_length=50, verbose_name='Sayfa Yolu')),
                ('sayfa_adi', models.CharField(max_length=100, verbose_name='Sayfa Adı')),
                ('goruntuleme_tarihi', models.DateField(verbose_name='Görüntüleme Tarihi')),
                ('goruntuleme_saati', models.TimeField(verbose_name='Görüntüleme Saati')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP Hash (Anonim)')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
            ],
            options={
                'verbose_name': 'Sayfa Görüntüleme',
                'verbose_name_plural': 'Sayfa Görüntülemeleri',
                'ordering': ['-goruntuleme_tarihi', '-goruntuleme_saati'],
                'indexes': [models.Index(fields=['sayfa_yolu', 'goruntuleme_tarihi'], name='turnuva_say_sayfa_y_a5d82f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.IntegerField(verbose_name='Tur Numarası')),
                ('mac_sirasi', models.IntegerField(verbose_name='Maç Sırası (Tur içinde)')),
                ('takim1_tip', models.CharField(choices=[('basketbol', 'Basketbol'), ('futbol', 'Futbol')], max_length=10)),
                ('takim1_id', models.IntegerField(verbose_name='Takım 1 ID')),
                ('takim1_adi', models.CharField(max_length=100, verbose_name='Takım 1 Adı')),
                ('takim2_tip', models.CharField(choices=[('basketbol', 'Basketbol'), ('futbol', 'Futbol')], max_length=10)),
                ('takim2_id', models.IntegerField(verbose_name='Takım 2 ID')),
                ('takim2_adi', models.CharField(max_length=100, verbose_name='Takım 2 Adı')),
                ('takim1_skor', models.IntegerField(blank=True, null=True, verbose_name='Takım 1 Skoru')),
                ('takim2_skor', models.IntegerField(blank=True, null=True, verbose_name='Takım 2 Skoru')),
                ('tarih', models.DateTimeField(blank=True, null=True, verbose_name='Maç Tarihi')),
                ('yer', models.CharField(blank=True, max_length=200, verbose_name='Maç Yeri')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('oynandi', 'Oynandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Maç Durumu')),
                ('turnuva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maclar', to='turnuva.turnuva', verbose_name='Turnuva')),
            ],
            options={
                'verbose_name': 'Maç',
                'verbose_name_plural': 'Maçlar',
                'ordering': ['turnuva', 'tur', 'mac_sirasi'],
                'indexes': [models.Index(fields=['turnuva', 'tur', 'mac_sirasi'], name='turnuva_mac_turnuva_0cf488_idx')],
            },
        ),
    ]
