# Generated by Django 5.2.15 on 2026-06-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnuva', '0003_siteayar_turnuva_sayfagoruntuleme_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteayar',
            name='countdown_alt_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Geri Sayım Alt Başlık'),
        ),
        migrations.AddField(
            model_name='siteayar',
            name='countdown_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Geri Sayım Başlık'),
        ),
        migrations.AddField(
            model_name='siteayar',
            name='countdown_ust_baslik',
            field=models.CharField(blank=True, max_length=200, verbose_name='Geri Sayım Üst Başlık'),
        ),
    ]
